const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COOLLECTIONS_FAILURE: 'FETCH_COOLLECTIONS_FAILURE'
}

export default ShopActionTypes;